### ISSUE TITLE
Colocar o menu (nav) disponível em todas as telas e em todo momento

### ISSUE THREAD

**Issue by jpoliveira12345** [comppet-ufu/comppet#27]
- Para os usuários experientes, ficar rolando para baixo para entrar em uma página a partir da home ter que rolar pode ser estressante (e.g. Home)

- O menu superior (nav) não está disponível em algumas páginas (e.g. Quem Somos)

**Comment by Fziliotti** [comment]
Bons tópicos levantados!

Sua sugestão seria para resolver o primeiro tópico seria colocar um menu fixo na parte superior já no inicio da página por exemplo?

O segundo tópico nós ja devemos resolver antes de sexta!

**Comment by higoress** [comment]
O segundo tópico já esta resolvido.

**Comment by higoress** [comment]
vou fechar, qualquer coisa abra uma nova issue
